---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/actionlint.yaml
      - aqua/reviewdog.yaml
jobs:
  actionlint:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@dca1267d5844edc50b4ed717250ee9dba7dc6a1c # v0.4.2
    with:
      aqua_version: v2.3.1
      aqua_policy_config: aqua-policy.yaml
    permissions:
      pull-requests: write
      contents: read
