---
name: Release
on:
  push:
    tags: [v*]
jobs:
  release:
    uses: suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml@900ca573c11c589375527553edee097fd80dc9a4 # v0.4.0
    with:
      homebrew: true
      go-version: 1.20.1
      aqua_version: v1.38.0
      aqua_policy_config: aqua-policy.yaml
    secrets:
      gh_app_id: ${{ secrets.APP_ID }}
      gh_app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
    permissions:
      contents: write
      id-token: write
      actions: read
