---
name: test-main

on:
  push:
    branches: [main]

permissions: {}

jobs:
  test-main:
    uses: suzuki-shunsuke/go-test-workflow/.github/workflows/test.yaml@b5eca11eb556672e54d5f0ac6a4d6744630727bd # v0.4.2
    permissions:
      pull-requests: write
