---
name: test-main

on:
  push:
    branches: [main]

permissions: {}

jobs:
  test-main:
    uses: suzuki-shunsuke/go-test-workflow/.github/workflows/test.yaml@fd6e66427230606a7d71e686d01e3eed92ae5012 # v1.0.0
    permissions:
      pull-requests: write
