---
name: test-main

on:
  push:
    branches: [main]

permissions: {}

jobs:
  test-main:
    uses: suzuki-shunsuke/go-test-workflow/.github/workflows/test.yaml@ef3bf756c7e21e23d232b73fd7bab92c848455cf # v0.2.1
    permissions:
      pull-requests: write
