---
name: test-main

on:
  push:
    branches: [main]

permissions: {}

jobs:
  test-main:
    uses: suzuki-shunsuke/go-test-workflow/.github/workflows/test.yaml@3191fc67e2aa6426e4bccd25be69b9d80b47a007 # v1.0.1
    permissions:
      pull-requests: write
